# src/ui/rolling_heatmap_presets.py
"""
Rolling Heatmap curated preset and Custom membership catalog.

Purpose:
    Own curated row-key memberships for the Phase III Rolling Heatmap
    Selection & Catalog architecture.

Scope:
    This module is authoritative for curated membership metadata only:
      - default Custom row set
      - explicit Overview preset memberships
      - preset ordering / labels

    It does not own:
      - row classification metadata
      - Category / Scope / Window / Family filtering
      - thematic preset generation
      - numeric computation
      - rulebook semantics
      - signal scoring
      - rolling payload generation
      - display names
      - definitions / educational text
      - UI control rendering

Authority:
    All memberships are expressed as canonical rolling heatmap row_key values.
    These row keys must exist in rolling_heatmap_classification.ROW_CLASSIFICATION.

Important ownership boundary:
    Overview presets are explicit curated memberships.
    Thematic presets such as ST Trend, MT Trend, LT Trend, ST Momentum,
    MT Momentum, and LT Momentum are generated in rolling_heatmap_selection.py.
"""

from __future__ import annotations

from typing import Dict, List, Mapping, Tuple

try:
    from .rolling_heatmap_classification import ROW_CLASSIFICATION
except ImportError:  # pragma: no cover
    # Allows direct ad-hoc execution from repo root during manual verification.
    from src.ui.rolling_heatmap_classification import ROW_CLASSIFICATION


# ---------------------------------------------------------------------
# Custom default membership
# ---------------------------------------------------------------------
# Authoritative default row-key set for Custom mode.
#
# Custom is a saved/editable selection set at runtime, but restore-default
# behavior must resolve back to this catalog-owned definition.
CUSTOM_DEFAULT: List[str] = [

    "RSI_14",            # Momentum

    # Trend / directional bias
    "EMA_20",
    "EMA_50",
    "SMA_50",    
    "SMA_100",
    "SMA_200",
    "VWMA_20",

    # Trend strength / trend momentum
    "ADX_14",
    "MACD_12_26_9",

    # Momentum
    "STOCH_14_3_3",      # Momentum
    "ROC_20",            # Momentum

    # Volatility
    "BB_PCT_B",
    "BB_BW",

    # Volume / flow
    "MFI_14",
    "CMF_21",
    "OBV",
]


# ---------------------------------------------------------------------
# Explicit Overview preset memberships
# ---------------------------------------------------------------------
# Overview presets are intentionally curated row sets.
# They are not generated from Category filters.
#
# Thematic presets are generated later in rolling_heatmap_selection.py.
OVERVIEW_PRESETS: Mapping[str, List[str]] = {
    "ST Overview": [
        # Short-term trend / directional bias
        "EMA_10",
        "EMA_20",
        "HMA_9",
        "VWMA_10",

        # Short-term trend strength / pressure
        "ADX_9",
        "MACD_5_34_1",
        "BullBearPower_10",

        # Short-term momentum
        "RSI_10",
        "STOCH_5_3_3",
        "WILLR_5",
        "ROC_9",

        # Short-term volatility
        "BB_PCT_B_ST",
        "BB_BW_ST",

        # Short-term volume / money flow
        "MFI_10",
        "CMF_10",
    ],

    "MT Overview": [
        # Medium-term trend / directional bias
        "EMA_50",
        "SMA_50",
        "HMA_21",
        "VWMA_20",

        # Medium-term trend strength / pressure
        "ADX_14",
        "MACD_12_26_9",
        "BullBearPower_21",

        # Medium-term momentum
        "RSI_14",
        "RSI_21",
        "STOCH_14_3_3",
        "WILLR_14",
        "ROC_20",

        # Medium-term volatility
        "BB_PCT_B",
        "BB_BW",

        # Medium-term volume / money flow
        "MFI_14",
        "CMF_21",
        "OBV",
    ],

    "LT Overview": [
        # Long-term trend / directional bias
        "EMA_100",
        "EMA_200",
        "SMA_100",
        "SMA_200",
        "VWMA_50",

        # Long-term trend strength
        "ADX_20",
        "MACD_20_50_10",

        # Long-term momentum
        "RSI_30",
        "STOCH_21_5_5",
        "WILLR_20",
        "ROC_50",

        # Long-term volatility
        "BB_PCT_B_LT",
        "BB_BW_LT",

        # Long-term volume / money flow
        "MFI_30",
        "CMF_50",
        "OBV",
    ],
}


# ---------------------------------------------------------------------
# Locked v1 preset dropdown order
# ---------------------------------------------------------------------
# Overview presets are explicit curated memberships above.
# Thematic presets in this order are generated by the selection layer.
PRESET_ORDER: Tuple[str, ...] = (
    "ST Overview",
    "MT Overview",
    "LT Overview",
    "ST Trend",
    "MT Trend",
    "LT Trend",
    "ST Momentum",
    "MT Momentum",
    "LT Momentum",
)


# ---------------------------------------------------------------------
# Lightweight validation helpers
# ---------------------------------------------------------------------
# These helpers validate curated membership metadata only. They do not
# resolve modes, apply filters, or generate thematic presets.
def get_explicit_preset_names() -> List[str]:
    """Return explicit curated preset names in locked dropdown order."""
    return [name for name in PRESET_ORDER if name in OVERVIEW_PRESETS]


def get_unknown_membership_keys() -> Dict[str, List[str]]:
    """
    Return unknown row keys referenced by curated memberships.

    Empty lists indicate that curated memberships are aligned with
    ROW_CLASSIFICATION.
    """
    known = set(ROW_CLASSIFICATION.keys())

    unknown: Dict[str, List[str]] = {
        "CUSTOM_DEFAULT": [row_key for row_key in CUSTOM_DEFAULT if row_key not in known]
    }

    for preset_name, row_keys in OVERVIEW_PRESETS.items():
        unknown[preset_name] = [row_key for row_key in row_keys if row_key not in known]

    return unknown


def validate_curated_memberships() -> None:
    """
    Raise ValueError if any curated membership references an unknown row_key.

    This is intended for manual verification and later unit-test coverage.
    """
    unknown = get_unknown_membership_keys()
    failures = {name: keys for name, keys in unknown.items() if keys}

    if failures:
        raise ValueError(f"Unknown row_key(s) in curated memberships: {failures}")